# Generated by Django 5.1.7 on 2025-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='special_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
