# Generated by Django 5.1.7 on 2025-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_one_to_one',
            field=models.BooleanField(default=False),
        ),
    ]
