# Generated by Django 5.1.7 on 2025-04-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0002_conversation_special_identifier'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_bots_m_convers_96e94d_idx',
        ),
    ]
