# Generated by Django 5.1.7 on 2025-03-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0002_conversation_is_one_to_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
